# Generated by Django 5.2.12 on 2026-03-26 05:19

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def populate_workflow_fields(apps, schema_editor):
    UserProject = apps.get_model('projects', 'UserProject')
    status_map = {
        'REQUESTED': 'pending',
        'APPROVED': 'approved',
        'IN_PROGRESS': 'in_progress',
        'COMPLETED': 'completed',
    }

    for user_project in UserProject.objects.select_related('project').all():
        total_price = user_project.total_price or user_project.custom_price or user_project.project.base_price or Decimal('0.00')
        total_price = Decimal(total_price).quantize(Decimal('0.01'))
        installment_1 = (total_price * Decimal('0.30')).quantize(Decimal('0.01'))
        installment_2 = (total_price * Decimal('0.40')).quantize(Decimal('0.01'))
        installment_3 = total_price - installment_1 - installment_2

        user_project.total_price = total_price
        user_project.installment_1 = installment_1
        user_project.installment_2 = installment_2
        user_project.installment_3 = installment_3
        user_project.status = status_map.get(user_project.status, user_project.status)
        if user_project.status == 'pending':
            user_project.current_stage = 1
        elif user_project.status == 'approved':
            user_project.current_stage = 1
        elif user_project.status == 'in_progress':
            user_project.current_stage = 2
        else:
            user_project.current_stage = 4
        user_project.save(update_fields=[
            'total_price',
            'installment_1',
            'installment_2',
            'installment_3',
            'status',
            'current_stage',
        ])


def reverse_populate_workflow_fields(apps, schema_editor):
    UserProject = apps.get_model('projects', 'UserProject')
    reverse_status_map = {
        'pending': 'REQUESTED',
        'approved': 'APPROVED',
        'in_progress': 'IN_PROGRESS',
        'mid_stage': 'IN_PROGRESS',
        'completed': 'COMPLETED',
        'delivered': 'COMPLETED',
    }

    for user_project in UserProject.objects.all():
        user_project.custom_price = user_project.total_price
        user_project.status = reverse_status_map.get(user_project.status, user_project.status)
        user_project.save(update_fields=['custom_price', 'status'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='current_stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Stage 1'), (2, 'Stage 2'), (3, 'Stage 3'), (4, 'Delivery')], default=1),
        ),
        migrations.AddField(
            model_name='userproject',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userproject',
            name='installment_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userproject',
            name='installment_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userproject',
            name='installment_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userproject',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userproject',
            name='payment_requested_for_stage',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Stage 1'), (2, 'Stage 2'), (3, 'Stage 3'), (4, 'Delivery')], null=True),
        ),
        migrations.AlterField(
            model_name='projectcatalog',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('mid_stage', 'Mid Stage'), ('completed', 'Completed'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
        migrations.RunPython(populate_workflow_fields, reverse_populate_workflow_fields),
        migrations.RemoveField(
            model_name='userproject',
            name='custom_price',
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_action_logs', to=settings.AUTH_USER_MODEL)),
                ('user_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='projects.userproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('approval', 'Approval'), ('payment', 'Payment'), ('progress', 'Progress'), ('stage', 'Stage Transition'), ('delivery', 'Delivery'), ('system', 'System')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('user_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.userproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
