# Generated by Django 5.2.12 on 2026-03-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_userproject_custom_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproject',
            name='payment_proof',
            field=models.FileField(blank=True, upload_to='payment-proofs/'),
        ),
        migrations.AddField(
            model_name='userproject',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verification', 'Verification'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
