# Generated by Django 5.2.12 on 2026-03-26 05:19

from decimal import Decimal

import django.utils.timezone
from django.db import migrations, models


def migrate_payment_workflow(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    UserProject = apps.get_model('projects', 'UserProject')

    type_map = {
        'ADVANCE': ('installment_1', 1),
        'FINAL': ('installment_3', 3),
    }
    status_map = {
        'PENDING': 'pending',
        'SUCCESS': 'success',
        'FAILED': 'failed',
    }

    for payment in Payment.objects.select_related('user_project').all():
        mapped_type, mapped_stage = type_map.get(payment.type, ('installment_1', 1))
        payment.type = mapped_type
        payment.stage = mapped_stage
        payment.status = status_map.get(payment.status, payment.status)
        if payment.status == 'success' and not payment.paid_at:
            payment.paid_at = payment.created_at
        payment.requested_at = payment.created_at
        payment.save(update_fields=['type', 'stage', 'status', 'paid_at', 'requested_at'])

    for user_project in UserProject.objects.all():
        successful = Payment.objects.filter(user_project_id=user_project.id, status='success').order_by('stage')
        paid_amount = sum((payment.amount for payment in successful), Decimal('0.00'))
        user_project.paid_amount = paid_amount
        if successful.filter(stage=3).exists():
            user_project.status = 'completed'
            user_project.current_stage = 4
        elif successful.filter(stage=1).exists():
            user_project.status = 'in_progress'
            user_project.current_stage = 2
        user_project.save(update_fields=['paid_amount', 'status', 'current_stage'])


def reverse_migrate_payment_workflow(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    type_map = {
        'installment_1': 'ADVANCE',
        'installment_2': 'FINAL',
        'installment_3': 'FINAL',
    }
    status_map = {
        'requested': 'PENDING',
        'pending': 'PENDING',
        'success': 'SUCCESS',
        'failed': 'FAILED',
    }

    for payment in Payment.objects.all():
        payment.type = type_map.get(payment.type, payment.type)
        payment.status = status_map.get(payment.status, payment.status)
        payment.save(update_fields=['type', 'status'])


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        ('projects', '0003_remove_userproject_custom_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Stage 1'), (2, 'Stage 2'), (3, 'Stage 3'), (4, 'Delivery')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='requested', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('installment_1', 'Installment 1'), ('installment_2', 'Installment 2'), ('installment_3', 'Installment 3')], max_length=20),
        ),
        migrations.RunPython(migrate_payment_workflow, reverse_migrate_payment_workflow),
    ]
